Add a Testing Guide
metalbear-co/mirrord.dev pull request #16
Opened 2022-06-30 05:34 UTC by infiniteregrets

2022-06-30 07:42 UTC, aviramha commented
I think we should split it to setup a kubernetes environment so an user can understand they can use any k8s cluster they want (with the caveat they'll need to push the built image to be available there).
Formatting needs to be improved - more sections, some snippets issues etc.

2022-06-30 19:21 UTC, aviramha requested changes

2022-06-30 19:21 UTC, aviramha commented on content/docs/developer/testing/index.md
> +## Setup Environment
Start with listing the pre-requisites (Rust version, docker, kubernetes cluster [local/or remote])

2022-06-30 19:21 UTC, aviramha commented on content/docs/developer/testing/index.md
> +## Setup Environment
point to a guide how to setup a kubernetes cluster (the guide you wrote)

2022-06-30 19:21 UTC, aviramha commented on content/docs/developer/testing/index.md
> +### Run E2E tests
Upper section

2022-07-04 18:38 UTC, eyalb181 requested changes

2022-07-04 18:38 UTC, eyalb181 commented on content/docs/developer/testing/index.md
> +### Setup a k8s Cluster
Should be Kubernetes (for consistency's sake)

2022-07-04 18:38 UTC, eyalb181 commented on content/docs/developer/testing/index.md
> +- [Minikube](https://minikube.sigs.k8s.io/)
A. [Kind](https://kind.sigs.k8s.io/docs/user/quick-start/) is also a good option
B. I think our default is back to being Minikube? @aviramha

2022-07-04 18:38 UTC, eyalb181 commented on content/docs/developer/testing/index.md
> +kubectl config use-context your-context
I thought we were conforming to docker-desktop (or minikube) for the entire guide?

2022-07-04 18:38 UTC, eyalb181 commented on content/docs/developer/testing/index.md
> +### Docker Desktop
Make sure to sort out the heading hierarchy here. Docker Desktop and Preparing a cluster should be subheadings of Setup a Kubernetes cluster

2022-07-04 18:38 UTC, eyalb181 commented on content/docs/developer/testing/index.md
> +### Build mirrord-agent
I would specify "Build mirrord-agent Docker image", and add a note as to why we're not building the actual Rust library

2022-07-04 18:38 UTC, eyalb181 commented on content/docs/developer/testing/index.md
> +### Build & run mirrord
Build and Run mirrord*

2022-07-04 18:38 UTC, eyalb181 commented on content/docs/developer/testing/index.md
> +On Nightly toolchain -
I would remove this sentence, it's confusing and evident from the next line anyway

2022-07-04 18:38 UTC, eyalb181 commented on content/docs/developer/testing/index.md
> +```js
Why is app.yaml collapsible but app.js isn't?

2022-07-04 18:38 UTC, eyalb181 commented on content/docs/developer/testing/index.md
> +docker tag agent-image test
Is this necessary? Isn't it created as 'test' given the build command you provided?

2022-07-05 05:59 UTC, infiniteregrets commented on content/docs/developer/testing/index.md
> +- [Minikube](https://minikube.sigs.k8s.io/)
Local testing was honestly quite easy with docker, didnt have to configure much. But I believe we should include docs for minikube and docker both. Lmk!

2022-07-21 07:41 UTC, aviramha commented
Stale for too long, let's merge this then re-iterate later on.

2022-07-21 07:41 UTC, merged