Add alternative solution for go binaries
metalbear-co/mirrord.dev pull request #160
Opened 2023-09-08 12:04 UTC by kevincali

Related to https://github.com/metalbear-co/mirrord/issues/1921

2023-09-08 12:06 UTC, kevincali commented on content/docs/overview/faq.md
> +3. If you are running mirrord on MacOS and the executable you are running is protected by
I wasn't sure if I should also add [the mentioned](https://github.com/metalbear-co/mirrord/issues/1921#issuecomment-1711342667)  VSCode build flag solution and the CLI oneliner, so for now I omitted it.

If you also want it in please tell me where I should put it. 
It felt wrong to put it in the edited paragraph, maybe it should be in a separate section or so :thinking:?

2023-09-08 13:51 UTC, eyalb181 requested changes

2023-09-08 13:51 UTC, eyalb181 commented on content/docs/overview/faq.md
> +   Using `go run` is not possible at the moment - please follow [this issue](https://github.com/metalbear-co/mirrord/issues/1922) for updates.
```suggestion
   On Linux, using `go run` is not possible at the moment - please follow [this issue](https://github.com/metalbear-co/mirrord/issues/1922) for updates.   
```

2023-09-08 13:52 UTC, eyalb181 commented on content/docs/overview/faq.md
> +3. If you are running mirrord on MacOS and the executable you are running is protected by
I think the CLI one-liner is implied from the `go build -ldflags...` snippet - maybe just add the VSCode bit in parentheses afterwards, i.e. (in VSCode, this can be done using...)?

2023-09-11 09:54 UTC, eyalb181 approved these changes

2023-09-11 09:54 UTC, eyalb181 commented
Looks great, appreciate the contribution!

2023-09-11 09:54 UTC, merged