Add docs for env vars
metalbear-co/mirrord.dev pull request #17
Opened 2022-07-01 18:27 UTC by infiniteregrets

2022-07-03 11:36 UTC, eyalb181 requested changes

2022-07-03 11:36 UTC, eyalb181 commented on content/docs/reference/env/index.md
> +To include/exclude environment variables selectively, use the `--override-env-vars-include` flag to include and `--override-env-vars-exclude` to exclude with environment variables specified in a `sem
Separated*

2022-07-03 11:36 UTC, eyalb181 commented on content/docs/reference/env/index.md
> +mirrord lets you run a local process in the context of remote environment i.e environment variables present in the remote pod will be loaded into the local process.
I'd add an example of a use case here, i.e. why do we even have this feature? Something like:
For example, if you want your local process to access a remote database, the connection string configured in the remote pod's environment variable can be used by your local process.

2022-07-03 11:36 UTC, eyalb181 commented on content/docs/reference/env/index.md
> +>>> print(os.environ['MIRRORD_FAKE_VAR_FIRST'])
Kind of a weird example in my opinion - is "MIRRORD_FAKE_VAR_FIRST" populated with "mirrord.is.running" in the remote pod? Is the reader supposed to know that somehow? Consider replacing with more self-explanatory values, for example ENV_VAR1=remote-value (important that the env var doesn't have 'mirrord' in its name, since it's not a mirrord-related env var).

2022-07-03 19:20 UTC, infiniteregrets commented on content/docs/reference/env/index.md
> +>>> print(os.environ['MIRRORD_FAKE_VAR_FIRST'])
Pushed the example to usage

2022-07-04 11:06 UTC, eyalb181 approved these changes

2022-07-04 18:20 UTC, merged