Contact us from
metalbear-co/mirrord.dev pull request #172
Opened 2023-10-08 22:02 UTC by t4lz

Closes #171

Everything is copied from other pages, mostly from the waitlist form. ChatGPT helped me change it.
Didn't try to design it a lot, let me know if there is a different design you want for the form.

Todo: setup a backend endpoint for the form.

2023-10-08 22:04 UTC, t4lz commented
Marked as ready to get a cloudflare preview link, but this is a WIP.

2023-10-09 08:37 UTC, eyalb181 requested changes

2023-10-09 08:37 UTC, eyalb181 commented on assets/css/site.css
> -/*! tailwindcss v3.2.4 | MIT License | https://tailwindcss.com*/
I'm not sure you're supposed to commit this, maybe try to revert and see if the cloudflare still looks okay.

2023-10-09 08:37 UTC, eyalb181 commented on layouts/_default/contact.html
> +          <div x-bind:class="(submitedMessage != null ? '' : 'scale-y-0') + ' transition py-3 text-center origin-top'">
```suggestion
          <div x-bind:class="(submittedMessage != null ? '' : 'scale-y-0') + ' transition py-3 text-center origin-top'">
```

2023-10-09 08:37 UTC, eyalb181 commented on layouts/_default/contact.html
> +                Submit {{ partial (printf "svg/icon-%s.svg" "waitlist") (dict "class" "w-6 h-6 text-current") }}
Doesn't look great with the icon - try spacing them out, or removing either the text or the icon, and seeing what looks best

2023-10-09 08:37 UTC, eyalb181 commented on config/_default/menus/menus.yaml
> +- identifier: contact
Please add to the footer as well

2023-10-09 08:37 UTC, eyalb181 commented on layouts/_default/contact.html
> +            <p class="mb-1">Email</p>
It's weird that the fields have both a label and a placeholder - I'd leave just the label (and change Email to Work Email)

2023-10-09 10:24 UTC, t4lz commented on layouts/_default/contact.html
> +          <div x-bind:class="(submitedMessage != null ? '' : 'scale-y-0') + ' transition py-3 text-center origin-top'">
done https://github.com/metalbear-co/mirrord.dev/pull/172/commits/b94f46d69617fa25e16812a9a0a539ed121db9ca

2023-10-09 10:25 UTC, t4lz commented on layouts/_default/contact.html
> +                Submit {{ partial (printf "svg/icon-%s.svg" "waitlist") (dict "class" "w-6 h-6 text-current") }}
Added spacing in https://github.com/metalbear-co/mirrord.dev/pull/172/commits/255b1fc010d443fbb714524b96fc76f84eadf421, is it better now?

2023-10-09 10:26 UTC, t4lz commented on config/_default/menus/menus.yaml
> +- identifier: contact
Done in https://github.com/metalbear-co/mirrord.dev/pull/172/commits/e7d3dbc2e54020c718ae9d949ec05c7a7cd7f392

2023-10-09 10:27 UTC, t4lz commented on layouts/_default/contact.html
> +            <p class="mb-1">Email</p>
Done in https://github.com/metalbear-co/mirrord.dev/pull/172/commits/863fe1cf22778676aabea54a2cac3d09cac1b879

2023-10-09 16:37 UTC, t4lz commented on yarn.lock
Is this ok to commit or should I try and see if now cloudflare preview works without these changes (it didn't initially but maybe that was unrelated).

2023-10-09 16:39 UTC, eyalb181 requested changes

2023-10-09 16:39 UTC, eyalb181 commented on layouts/_default/contact.html
> +            <label for="name">Your Name</label>
```suggestion
            <label for="name">Name</label>
```

2023-10-09 16:39 UTC, eyalb181 commented on yarn.lock
Lets try without

2023-10-09 16:40 UTC, eyalb181 commented on layouts/_default/contact.html
> +  {{- partial "form/handle-submission.html" (dict "context" . "prefix" "contact" "successMessage" "Thank you for contacting us! We'll get back to you soon." "failureMessage" "Failed to send your mess
Is this still necessary? Thought it was handled by web3forms?

2023-10-09 16:41 UTC, t4lz commented on layouts/_default/contact.html
> +  {{- partial "form/handle-submission.html" (dict "context" . "prefix" "contact" "successMessage" "Thank you for contacting us! We'll get back to you soon." "failureMessage" "Failed to send your mess
You're right.

2023-10-09 16:50 UTC, t4lz commented on yarn.lock
Looks like it's working without.

2023-10-09 16:52 UTC, eyalb181 approved these changes

2023-10-09 16:52 UTC, merged