Add FAQ entry on FS exceptions.
metalbear-co/mirrord.dev pull request #182
Opened 2023-10-20 15:13 UTC by t4lz

close #179

2023-10-22 10:38 UTC, eyalb181 requested changes

2023-10-22 10:38 UTC, eyalb181 commented on content/docs/overview/faq.md
> +### A local file is read instead of a remote one, or my application cannot find a file that is only present in the cluster
```suggestion
### My application is trying to read a file locally even though `fs` is set to `remote` (or vice versa)
```

2023-10-22 10:38 UTC, eyalb181 commented on content/docs/overview/faq.md
> +There are pre-defined exceptions to the set FS mode. That means that some files are read locally by default
This is way too wordy in my opinion. I would just put:
mirrord has a list of paths that are read locally by default, and another list that are read remotely by default, regardless of the configured `fs` mode. You can override this behavior in the configuration. 

Here you can find all the pre-defined exceptions...

In order to override...

2023-10-23 07:22 UTC, t4lz commented on content/docs/overview/faq.md
> +There are pre-defined exceptions to the set FS mode. That means that some files are read locally by default
https://github.com/metalbear-co/mirrord.dev/pull/182/commits/f47c45e9ae6cb5d9e281c79d1765719dad7c490a

2023-10-23 07:32 UTC, eyalb181 requested changes

2023-10-23 07:42 UTC, t4lz commented on content/docs/overview/faq.md
> +### My application is trying to read a file locally even though `fs` is set to `remote`
Actually `"remote"` is not a real mode, and also there are two modes that should read in the cluster. Moreover, saying it that way might give users the wrong impression that they have to set the `fs` config to something in order for mirrord to read remotely.
```suggestion
### My application is trying to read a file locally instead of in the cluster even though I did not configure mirrord to do that
```
What do you think?

2023-10-23 09:40 UTC, eyalb181 commented on content/docs/overview/faq.md
> +### My application is trying to read a file locally even though `fs` is set to `remote`
in the cluster => from the cluster/remote pod
And I'd drop everything after "in the cluster", I think it's implied

2023-10-23 10:12 UTC, t4lz commented on content/docs/overview/faq.md
> +### My application is trying to read a file locally even though `fs` is set to `remote`
```suggestion
### My application is trying to read a file locally instead of from the cluster
```

2023-10-23 10:13 UTC, eyalb181 approved these changes

2023-10-23 10:14 UTC, merged