Address GKE operator connectivity issue
metalbear-co/mirrord.dev pull request #206
Opened 2023-12-24 05:06 UTC by infiniteregrets

2023-12-24 15:56 UTC, eyalb181 requested changes

2023-12-24 15:56 UTC, eyalb181 commented on content/docs/overview/faq.md
> +### `mirrord operator status` fails with `503 Service Unavailable` on GKE
This is a mirrord for Teams issue, so not relevant to this FAQ. Please create an FAQ page under the `mirrord for Teams` section, and put this question under a Common Issues section.

2023-12-24 15:56 UTC, eyalb181 commented on content/docs/overview/faq.md
> +If private networking enabled, it is likely due to firewall rules blocking the mirrord operator's API service from the API server. To fix this, add a firewall rule that allows your cluster's master n
```suggestion
If private networking is enabled, it is likely due to firewall rules blocking the mirrord operator's API service from the API server. To fix this, add a firewall rule that allows your cluster's master nodes to access TCP port 3000 in your cluster's pods. Please refer to the [GCP docs](https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#add_firewall_rules) for information.
```

2023-12-29 07:06 UTC, infiniteregrets commented on content/docs/overview/faq.md
> +### `mirrord operator status` fails with `503 Service Unavailable` on GKE
Is "General" more suited here instead of "Common issues"?

2023-12-29 07:12 UTC, infiniteregrets commented
Accidentally commited same js twice one in the HTML file and other in alert.js, so removing that

2023-12-31 08:26 UTC, eyalb181 requested changes

2023-12-31 08:26 UTC, eyalb181 commented on layouts/partials/header/alert.html
> -<script>
?

2023-12-31 08:26 UTC, eyalb181 commented on content/docs/teams/FAQ/index.md
> +## General
```suggestion
## Common Issues
```

2023-12-31 08:34 UTC, infiniteregrets commented on layouts/partials/header/alert.html
> -<script>
I already commented here:

> Accidentally commited same js twice one in the HTML file and other in alert.js, so removing that here

2023-12-31 08:54 UTC, eyalb181 commented on content/docs/overview/faq.md
> +### `mirrord operator status` fails with `503 Service Unavailable` on GKE
Just noticed you commented here. I don't think so, it's a very specific issue.

2023-12-31 08:54 UTC, eyalb181 approved these changes

2023-12-31 09:25 UTC, merged