added back to top fab
metalbear-co/mirrord.dev pull request #233
Opened 2024-02-07 10:30 UTC by FazeenIjaz

Add a FAB to scroll back to top.

2024-02-07 10:32 UTC, aviramha commented
Thanks for sending this. Can you remove unrelated changes (css, lock files) and leave only needed changes so it'll be easier to review?

2024-02-07 10:52 UTC, aviramha requested changes
Thanks, still some left over changes that needs to rollback.

2024-02-07 10:52 UTC, aviramha commented on layouts/index.html
> +  {{- partial "sections/section-hero.html" . }} {{- partial
Change back to previous formatting.

2024-02-07 10:52 UTC, aviramha commented on assets/css/site.css
Remove from PR

2024-02-07 10:52 UTC, aviramha commented on package-lock.json
Remove from PR

2024-02-07 10:52 UTC, aviramha commented on yarn.lock
Remove from PR

2024-02-07 13:26 UTC, aviramha commented
Nothing from your side. I'm waiting to run it locally to see that it works as intended before merigng.

2024-02-07 14:08 UTC, infiniteregrets commented
Hey @FazeenIjaz! Thanks for making this change. I ran your branch and found that this button does not show up on the documentation page or any other page. Could you please look into that if possible?

Also, the button is really small and looks a bit odd per the rest of the UI. Can you please try to resize the button a bit, move it a little to the left and add some padding 🙂 

<img width="86" alt="Screenshot 2024-02-07 at 9 06 51 AM" src="https://github.com/metalbear-co/mirrord.dev/assets/65443164/8edcf184-4cf1-4ab9-b060-24d9e4cd617f">

2024-02-12 15:38 UTC, infiniteregrets commented
Hi @FazeenIjaz I have made some changes on my end here to adjust the UI. I appreciate you implementing this! Thanks for your contribution (:

2024-02-12 15:40 UTC, infiniteregrets approved these changes

2024-02-12 15:42 UTC, aviramha approved these changes

2024-02-12 15:43 UTC, merged