Document sessions feature.
metalbear-co/mirrord.dev pull request #252
Opened 2024-03-01 18:09 UTC by meowjesty

- Issue: [#456](https://github.com/metalbear-co/operator/issues/456)

(wip)

2024-03-04 16:38 UTC, eyalb181 requested changes

2024-03-04 16:38 UTC, eyalb181 commented on content/docs/reference/sessions.md
> +`mirrord operator session` cli commands. These allow users to manually close Operator sessions
```suggestion
`mirrord operator session` CLI commands. These allow users to manually close Operator sessions
```

2024-03-04 16:38 UTC, eyalb181 commented on content/docs/reference/sessions.md
> +---
Reference isn't the place for this, it's more for deep technical dives than for practical user guides. The docs below should be split between Using mirrord (for end users - maybe combine it with the See Active Sessions page) and Managing mirrord (for admins, so the policies part, combine with the existing Policies page)

2024-03-04 17:03 UTC, t4lz commented on content/docs/reference/sessions.md
> +### `sessions` policies
Let's not call it "policies" as that's not how the k8s docs call it, and also it might cause confusion with mirrord policies.

```suggestion
### `sessions` RBAC
```

2024-03-04 17:16 UTC, meowjesty commented on content/docs/reference/sessions.md
> +---
For the admin part:

Should we show this config in the policies page, or make a `MirrordPolicy` yaml like the other examples in the page?

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator-user
rules:
- apiGroups:
  - operator.metalbear.co
  resources:
  - sessions
  verbs:
  - deletecollection
  - delete
```

2024-03-04 17:30 UTC, meowjesty commented on content/docs/reference/sessions.md
> +---
Hmm, so should I not mention the RBAC part anywhere, other than in the `How do I configure Role Based Access Control for ...` part? Basically, put the `sessions` there on the example yaml?

2024-03-04 17:46 UTC, t4lz commented on content/docs/reference/sessions.md
> +---
You should keep all the contents of this file. Eyal said not to put them here though, and to split them between the `USING MIRRORD` and the `MANAGING MIRRORD` sections. The first part of this page (currently titled `Overview`), should be In `USING MIRROD`. You could either add it to the `See Active Sessions` page (and then consider modifying that page name), or add a new `Stop Active Sessions` (or whatever) page and put it there. The second part of this page (currently titled `sessions policies`) should be in `MANAGING MIRRORD`, IDK if in the `Security` page, but definitely not in the `Policies` page.

2024-03-04 17:56 UTC, meowjesty commented on content/docs/reference/sessions.md
> +---
I think moving the `sessions.md` page under `Using mirrord` section would be nice? When I'm reading docs, I don't want to jump around that much. Give me a page with all the basics so I can run `mirrord operator sessions kill-all`, then, if the feature has tons of side-cases (like `target` has, but `sessions` doesn't), it's ok to link me to other pages where I can get a full picture.

2024-03-04 18:30 UTC, eyalb181 commented on content/docs/reference/sessions.md
> +---
I'm okay with having it all under `Using mirrord`, at least for starters

2024-03-04 18:36 UTC, meowjesty commented on content/docs/reference/sessions.md
> +---
Moved :package:

2024-03-04 18:51 UTC, eyalb181 commented on content/docs/reference/sessions.md
> +---
Still need to merge it with the "See active sessions" page

2024-03-04 20:24 UTC, meowjesty commented on content/docs/reference/sessions.md
> +---
Merged

2024-03-05 14:43 UTC, eyalb181 requested changes

2024-03-05 14:43 UTC, eyalb181 commented on content/docs/using-mirrord/sessions.md
> +Whenever a user starts mirrord with the `operator` feature enabled, the Operator assigns a
The first sentence here should be the first sentence of the whole page (before the 'see active sessions' title). Also, instead of with the "`operator` feature enabled" phrasing, use the "installed as part of mirrord for teams" phrasing

2024-03-05 14:51 UTC, meowjesty commented on content/docs/using-mirrord/sessions.md
> +Whenever a user starts mirrord with the `operator` feature enabled, the Operator assigns a
Better?

2024-03-05 16:03 UTC, eyalb181 requested changes

2024-03-06 14:38 UTC, merged