Use files from repo in tests guide
metalbear-co/mirrord.dev pull request #26
Opened 2022-09-01 15:22 UTC by t4lz

Currently, the reader is instructed to copy from the browser a new Resources Config file. However the shown outputs from `kubectl` list the service name from the file from the repo, not the file from the guide. Since the guide assumes the user is in the root directory of the project anyways (e.g. with mirrord-agent/Dockerfile), let's use the files from the project. This way, the reader does not have to copy files from the browser, and the output they see in the guide matches the output they get on their system.

2022-09-01 15:36 UTC, eyalb181 requested changes

2022-09-01 15:36 UTC, eyalb181 commented on content/docs/developer/testing/index.md
> +  <summary>tests/app.yaml</summary>
I don't love this guide using files in our tests/ directory (since they're meant to be used by the e2e tests and who knows how they'll change in the future). We do however have a sample/ directory, which already contains a node app, so maybe just copy the app.yaml over there (under an appropriately named subdirectory)

2022-09-01 15:56 UTC, t4lz commented on content/docs/developer/testing/index.md
> +  <summary>tests/app.yaml</summary>
Like this? https://github.com/metalbear-co/mirrord/pull/313

2022-09-01 16:27 UTC, t4lz commented on content/docs/developer/testing/index.md
> +- [Go](https://go.dev/)
Also added Go to prerequisites now. @eyalb181

2022-09-01 16:36 UTC, eyalb181 requested changes
Looks good, just see my note on the other PR (about the app.yaml path)

2022-09-02 08:01 UTC, eyalb181 approved these changes

2022-09-02 08:12 UTC, merged