add monitoring section
metalbear-co/mirrord.dev pull request #269
Opened 2024-04-10 15:26 UTC by aviramha

Pending operator release + chart release.

2024-04-10 15:36 UTC, Razz4780 requested changes

2024-04-10 15:36 UTC, Razz4780 commented on content/docs/managing-mirrord/monitoring/index.md
> +Log level is info by default, and can be altered via operator deployment env using `RUST_LOG` (directive)[https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html].
```suggestion
Log level is info by default, and can be altered via operator container environment using `RUST_LOG` [directive](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html).
```

2024-04-10 16:24 UTC, aviramha commented on content/docs/managing-mirrord/monitoring/index.md
> +To enable JSON logging, specify `json_log: true` under `operator` in the operator helm chart values.
No, we don't support any complex configuration in the setup.

2024-04-10 16:26 UTC, Razz4780 approved these changes

2024-04-10 17:03 UTC, eyalb181 requested changes

2024-04-10 17:03 UTC, eyalb181 commented on content/docs/managing-mirrord/monitoring/index.md
> +Log level is info by default, and can be altered via operator container environment using `RUST_LOG` [directive](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.h
```suggestion
The log level is `INFO` by default, and can be changed via operator container environment using the `RUST_LOG` [directive](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html).
```

2024-04-10 17:03 UTC, eyalb181 commented on content/docs/managing-mirrord/monitoring/index.md
> +Log level is info by default, and can be altered via operator container environment using `RUST_LOG` [directive](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.h
You're sending the reader to do a Rust PhD with that link, could you just put an example instead?

2024-04-14 17:22 UTC, eyalb181 commented on content/docs/managing-mirrord/monitoring/index.md
> +The log level is `INFO` by default, and can be changed via operator container environment using the `RUST_LOG` [directive](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.E
```suggestion
The log level is `INFO` by default, and can be changed using the `RUST_LOG` environment variable in the Operator container, which takes values in the following format: `mirrord={log_level}` (e.g. `mirrord=debug`).
```

2024-04-14 17:57 UTC, eyalb181 approved these changes

2024-04-14 18:00 UTC, merged