queue splitting guide
metalbear-co/mirrord.dev pull request #337
Opened 2024-08-30 21:55 UTC by t4lz

2024-09-01 11:21 UTC, eyalb181 requested changes

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +mirrord to read messages from the queue. You probably don't want the local application to have to compete with the
I think this paragraph assumes some previous context. I would restructure it along the lines of:
"Two possible options are:
1. Simply running your application with mirrord without any special configuration. In this case, your local application will compete with the remote target for queue messages.
2. Running your application with copy-scaledown [link). This will result in..."

Another option is Queue Splitting...

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +With _mirrord for Teams_, queue messages can be split between (possibly multiple) mirrord users, and the deployed
No need to mention mfT - that's what the tags are for.

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +With _mirrord for Teams_, queue messages can be split between (possibly multiple) mirrord users, and the deployed
What does "possibly multiple" mean when qualifying a plural noun?

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +Users can set attribute filters in their mirrord configurations, and only get queue messages that have attributes
```suggestion
Users can define a filter in their mirrord configurations, and their local app will only read queue messages that have match that filter
```

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +So far queue splitting is available for [Amazon SQS](https://aws.amazon.com/sqs/) queues. Pretty soon we'll support
Format this is a note, i.e.  `> **_NOTE:_**  The note content.`

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +So far queue splitting is available for [Amazon SQS](https://aws.amazon.com/sqs/) queues. Pretty soon we'll support
```suggestion
So far queue splitting is available for [Amazon SQS](https://aws.amazon.com/sqs/). Pretty soon we'll support
```

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +kafka queues as well.
```suggestion
Kafka as well.
```

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +When sqs splitting is enabled during installation, some additional resources are created, and the SQS component of
```suggestion
When SQS splitting is enabled during installation, some additional resources are created, and the SQS component of
```

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +## SQS-enabled mirrord operator installation
Enabling Queue Splitting in your Cluster

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +In order to use the queue splitting feature, some extra values need be provided during the installation.
```suggestion
In order to use the queue splitting feature, some extra values need be provided during the installation of the mirrord Operator.
```

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +When sqs splitting is enabled during installation, some additional resources are created, and the SQS component of
Capitalize sqs throughout the post

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +the mirrord operator is started.
Capitalize Operator throughout the post

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +The ARN of the IAM role has to be passed when installing the operator. When installing with helm, the ARN is passed
Capitalize helm throughout the post

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +
How it works + Explanation + one or more diagrams

2024-09-01 11:21 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +Once all users stop filtering a queue (stop their mirrord runs), the temporary SQS queues that mirrord created will be
```suggestion
Once all users stop filtering a queue (i.e. end their mirrord sessions), the temporary SQS queues that mirrord created will be
```

2024-09-01 15:34 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting.md
> +mirrord to read messages from the queue. You probably don't want the local application to have to compete with the
How is this: https://github.com/metalbear-co/mirrord.dev/pull/337/commits/5e318893484e4bddda52d4fafa42098ea26dd415

2024-09-01 15:52 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting.md
> +## SQS-enabled mirrord operator installation
https://github.com/metalbear-co/mirrord.dev/pull/337/commits/25c98fcb12bc0c84b89f14044d7a49d0e80397db

2024-09-01 15:52 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting.md
> +the mirrord operator is started.
Also just "operator" when not occurring in "mirrord Operator" but by itself, like in "the Operator"? (Capitalizing in either of those cases seems weird to me)

2024-09-01 15:52 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting.md
> +The ARN of the IAM role has to be passed when installing the operator. When installing with helm, the ARN is passed
done in https://github.com/metalbear-co/mirrord.dev/pull/337/commits/2c09a8c59b84c272c82c2809e9c5820b772f9f38

2024-09-01 15:52 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting.md
> +So far queue splitting is available for [Amazon SQS](https://aws.amazon.com/sqs/) queues. Pretty soon we'll support
done in https://github.com/metalbear-co/mirrord.dev/pull/337/commits/63bf2867c4ebef86897a66e5e88324d745a22033

2024-09-01 17:08 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +the mirrord operator is started.
In which cases, "operator" alone? Or also "mirrord Operator"?

2024-09-01 17:10 UTC, eyalb181 requested changes

2024-09-01 17:10 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +title: "Queue Splitting"
General note - there are a lot of long blocks of text here, when you look at the Cloudflare preview. Try breaking the text up a bit more with new paragraphs, bullets, etc. For example, if you're listing out options for Helm and `mirrord setup`, don't do it in the same paragraph.

2024-09-01 18:41 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting.md
> +
Added in https://github.com/metalbear-co/mirrord.dev/pull/337/commits/c129fed5caf0bb1e9f6a851c13d31173c37411a0

2024-09-01 18:41 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting.md
> +title: "Queue Splitting"
Better [now](https://github.com/metalbear-co/mirrord.dev/pull/337/commits/f59c7d204f455a79491c02553941f30e3b75fba4)?

2024-09-01 18:41 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting.md
> +the mirrord operator is started.
Both cases are a bit weird to me, but capitalizing "operator" when not preceded with mirrord I don't get, so I'm making sure you want those occurrences capitalized as well.

2024-09-02 07:19 UTC, eyalb181 requested changes

2024-09-02 07:19 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +When a queue splitting session starts, the operator changes the target workload to consumer messages from a
```suggestion
When a queue splitting session starts, the operator changes the target workload to consume messages from a
```

2024-09-02 07:19 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +{{<figure src="before-splitting.png" class="bg-white center" alt="A K8s application that consumes messages from a queue">}}
I think you should change the direction of the "consume messages" arrows. I realize it's technically outgoing traffic, but it's clearer if it indicates the direction of the flow of data.

2024-09-02 07:19 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +A bit after a mirrord session ends, the operator will delete the temporary queue it created for it. When all
```suggestion
After a mirrord session ends, the operator will delete the temporary queue it created for it. When all
```

2024-09-02 07:19 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +### SQS Splitting
Seems like this whole bit doesn't mention the filters, either in the drawings or the text, i.e. that the operator decides which queue to write messages to based on the filter defined by the local app.

2024-09-02 07:19 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +## Permissions for target workloads
Shouldn't this and the next section be part of the "enabling queue splitting" section?

2024-09-02 07:19 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +Please follow AWS's documentation on how to do that:
```suggestion
Please follow [AWS's documentation on how to do that](https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html).
```

2024-09-02 07:19 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +- When installing with Helm, the ARN is passed
Is --set only an option for this argument, but not for the operator.sqsSplitting configuration?

2024-09-02 08:52 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting/index.md
> +- When installing with Helm, the ARN is passed
Can be used to set any value. Would you like it mentioned in both places or neither?

2024-09-02 08:52 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting/index.md
> +### SQS Splitting
https://github.com/metalbear-co/mirrord.dev/pull/337/commits/566fa5ec5ed8f3b2d3c0b593484a3a9da2b603fa

2024-09-02 08:52 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting/index.md
> +## Permissions for target workloads
Not in my opinion, since the last section is about installing the operator and creating the IAM roles and IAM/SQS policies it needs, whereas these to sections are about things that are needed to target a workload. These steps can be done at any point after the operator was installed, e.g. when a new service is created. They could be grouped under "Preparing a Target for Splitting", I don't know if that helps.

2024-09-02 08:56 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting.md
> +the mirrord operator is started.
Don't worry about it

2024-09-02 09:01 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +## Permissions for target workloads
The general point is that the titles are non-standard. Suppose I read How It Works and I want to use Queue Splitting - which sections do I need to read? Personally I'd look for a "Getting Started" section, which I guess "Enabling Queue Splitting in your Cluster" is close enough, but the others aren't.

2024-09-02 09:02 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +- When installing with Helm, the ARN is passed
Neither, and if you're already touching these areas, please make the phrasing consistent (with vs. via, this means setting vs. x should be set, etc.)

2024-09-02 09:03 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +### SQS Splitting
Can you add it to the drawing as well? e.g. "Send messages matching filter X",

2024-09-02 09:46 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting/index.md
> +- When installing with Helm, the ARN is passed
https://github.com/metalbear-co/mirrord.dev/pull/337/commits/b549fad30d00581f9b1983dce10667f1b7228510

2024-09-02 09:46 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting/index.md
> +## Permissions for target workloads
Ok, changed those sections to be part of the other section https://github.com/metalbear-co/mirrord.dev/pull/337/commits/3e7a2c95d207b26608de6f11d4698b42e7215d0a

2024-09-02 09:46 UTC, t4lz commented on content/docs/using-mirrord/queue-splitting/index.md
> +### SQS Splitting
Added

2024-09-02 09:51 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +## Permissions for target workloads
Actually, how about adding a Getting Started with Queue Splitting heading, and then make all of these subheadings on the same level?

2024-09-02 09:52 UTC, eyalb181 requested changes

2024-09-02 09:52 UTC, eyalb181 commented on content/docs/using-mirrord/queue-splitting/index.md
> +## Setting a Filter for a Mirrord Run
```suggestion
## Setting a Filter for a mirrord Run
```

2024-09-02 10:01 UTC, eyalb181 approved these changes

2024-09-02 10:05 UTC, merged