Update port forwarding docs for reverse portfwd
metalbear-co/mirrord.dev pull request #356
Opened 2024-10-14 16:40 UTC by gememma

2024-10-14 16:50 UTC, gememma commented
Latest commit: 	d058d99
Status:	 ✅  Deploy successful!
Preview URL:	https://99ceec53.mirrord-dev.pages.dev/
Branch Preview URL:	https://gemma-mbe-443-documentation.mirrord-dev.pages.dev/

2024-10-15 10:29 UTC, Razz4780 requested changes
A couple suggestions

2024-10-15 10:29 UTC, Razz4780 commented on content/docs/using-mirrord/port-forwarding.md
> +For example, to forward traffic from localhost:8080 to py-serv on port 80 (in targetless mode):
```suggestion
For example, to forward traffic from localhost:8080 to an incluster service py-serv listening on port 80:
```

2024-10-15 10:29 UTC, Razz4780 commented on content/docs/using-mirrord/port-forwarding.md
> +It also allows for reverse port forwarding, where traffic to a port on the target pod is forwarded to a local one, like so:
```suggestion
It also allows for reverse port forwarding, where traffic is redirected from a port on the target pod or workload to a local port, like so:
```

2024-10-15 10:29 UTC, Razz4780 commented on content/docs/using-mirrord/port-forwarding.md
> +
I'd add another example, like:

For example, to forward traffic from an incluster deployment py-serv listening on port 80 to localhost:8080:
```bash
mirrord port-forward --target deployment/py-serv -R 80:8080
```

2024-10-15 10:29 UTC, Razz4780 commented on content/docs/using-mirrord/port-forwarding.md
> +In addition, multiple ports can be forwarded in one direction or both directions simultaneously in the same command by providing each source and destination as a separate `-L` or `-R` argument.
```suggestion
In addition, multiple ports can be forwarded in one direction or both directions simultaneously in the same command by providing each source and destination as a separate `-L` or `-R` argument.

Regular port forwarding with an `-L` can be done in targetless mode and does not require specifying any target. Reverse port forwarding always requires a target.
```

2024-10-15 10:29 UTC, Razz4780 commented on content/docs/using-mirrord/port-forwarding.md
> +- Connections are made lazily, so a hostname may fail to resolve only after mirrord attempts to send it data.
```suggestion
- In regular port forwarding (`-L`) connections are made lazily and hostname resolution is attempted only data is sent to the local port.
```

2024-10-17 08:49 UTC, gememma commented on content/docs/using-mirrord/port-forwarding.md
> +In addition, multiple ports can be forwarded in one direction or both directions simultaneously in the same command by providing each source and destination as a separate `-L` or `-R` argument.
good catch 👀

2024-10-18 12:49 UTC, Razz4780 approved these changes

2024-10-18 12:49 UTC, merged