VoiceFlow User story
metalbear-co/mirrord.dev pull request #362
Opened 2024-11-20 10:54 UTC by Anita-ihuman

2024-11-20 13:14 UTC, eyalb181 commented
User photo and logo aren't showing here: https://e03c8a71.mirrord-dev.pages.dev/stories/

2024-11-20 13:17 UTC, eyalb181 commented on content/stories/voiceflow/index.md
> +title: "VoiceFlow User Story | Greg O'Grady"
You're missing a profile pic and an avatar. Look at the other user stories to see exactly how and where to put them. Note the profile pic has to be a cropped circle of the pic you added - you can probably use some online tool for it like this thing: https://crop-circle.imageonline.co/

2024-11-20 13:25 UTC, eyalb181 requested changes

2024-11-20 13:25 UTC, eyalb181 commented on content/stories/voiceflow/index.md
> +title: "VoiceFlow User Story | Greg O'Grady"
```suggestion
title: "Voiceflow User Story | Greg O'Grady"
```

2024-11-20 13:25 UTC, eyalb181 commented on content/stories/voiceflow/index.md
> +position: "Software Engineer | VoiceFlow"
Fix all instances of VoiceFlow to Voiceflow

2024-11-25 15:38 UTC, Anita-ihuman commented
@eyalb181 I believe I have gone through these reviews. Anymore comments?

2024-11-25 16:24 UTC, Anita-ihuman commented
> Please see if you can find a logo with the name of the company. Also it should be smaller - have a look at what it looks like in the preview site.

updated.

2024-11-25 16:32 UTC, eyalb181 approved these changes
Approved, well done

2024-11-25 20:31 UTC, merged