Add section to Kafka splitting config docs for loadFromSecret
metalbear-co/mirrord.dev pull request #376
Opened 2024-12-09 17:02 UTC by gememma

2024-12-09 17:05 UTC, gememma commented
link to relevant section in preview: https://gemma-mbe-565-update-kafka-s.mirrord-dev.pages.dev/docs/using-mirrord/queue-splitting/#mirrordkafkaclientconfig

2024-12-10 12:28 UTC, Razz4780 requested changes

2024-12-10 12:28 UTC, Razz4780 commented on content/docs/using-mirrord/queue-splitting/index.md
> +Property inheritance from the parent still occurs, and within each `MirrordKafkaClientConfig` properties in the `loadFromSecret` field are overwritten by those in `properties`.
```suggestion

Each key-value entry defined in secret's data will be included in the resulting `.properties` file. Property inheritance from the parent still occurs, and within each `MirrordKafkaClientConfig` properties loaded from the secret are overwritten by those in `properties`.
```

2024-12-10 12:28 UTC, Razz4780 commented on content/docs/using-mirrord/queue-splitting/index.md
> +The value for `loadFromSecret` is given in the form: "namespace/name".
```suggestion
The value for `loadFromSecret` is given in the form: `<secret-namespace>/<secret-name>`.
```

2024-12-10 13:24 UTC, Razz4780 approved these changes

2024-12-10 13:25 UTC, merged