Add HTTP Header Filter documentation.
metalbear-co/mirrord.dev pull request #52
Opened 2023-01-09 17:14 UTC by t4lz

Should only be merged once https://github.com/metalbear-co/mirrord/pull/843 is merged and released.

2023-01-09 19:58 UTC, eyalb181 requested changes

2023-01-09 19:58 UTC, eyalb181 commented on content/docs/reference/traffic/index.md
> +The HTTP header filter can be specified in the mirrord configuration by setting the incoming mode to
We don't want users to use the env var, so lets remove any mentions of it in the docs

2023-01-09 19:58 UTC, eyalb181 commented on content/docs/reference/traffic/index.md
> +When specified, all the headers of each HTTP request that arrives at the "impersonated" target are checked against
```suggestion
When specified, all the headers of each HTTP request that arrives at the remote target are checked against
```

You use remote later anyway, so at least this way it's clearer you're talking about the same thing

2023-01-09 19:58 UTC, eyalb181 commented on content/docs/reference/traffic/index.md
> +Currently only supporting HTTP version 1.
```suggestion
Currently only HTTP version 1 is supported.
```

2023-01-10 08:47 UTC, eyalb181 requested changes

2023-01-10 08:47 UTC, eyalb181 commented on content/docs/reference/traffic/index.md
> +The HTTP header filter can be specified in the mirrord configuration by setting the incoming mode to
```suggestion
The HTTP header filter can be specified in the mirrord configuration file by setting the incoming mode to
```

2023-01-10 08:47 UTC, eyalb181 commented on content/docs/reference/traffic/index.md
> +A filter cannot be specified via an argument in the command line interface.
I don't think we should mention this

2023-01-10 09:12 UTC, t4lz commented on content/docs/reference/traffic/index.md
> +A filter cannot be specified via an argument in the command line interface.
```suggestion
```

2023-01-10 14:09 UTC, eyalb181 approved these changes

2023-01-10 14:09 UTC, merged