Add target reference - #72
metalbear-co/mirrord.dev pull request #76
Opened 2023-05-08 20:16 UTC by t4lz

Add target reference, also explain targetless mode. #72.

2023-05-19 10:14 UTC, eyalb181 requested changes

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +There are several kinds of possible targets, that are explained below. There are also multiple ways to specify a
```suggestion
The several kinds of supported targets are detailed below. There are also multiple ways to specify a
```

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +target for mirrord - you can specify it in a configuration file, in an IDE dialog, or on CLI with an argument or an
```suggestion
target for mirrord: you can specify it in a configuration file, in an IDE dialog, or in the CLI with an argument or an
```

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +services from within the cluster, but you don't have any target that you want to "impersonate". When running
```suggestion
services from within the cluster, but you don't have any target that you want to "impersonate" - like when running an external utility or a new microservice. When running
```

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +will not mirror or steal incoming traffic, as a targetless agent is not connected to any kubernetes service and does not
```suggestion
will not mirror or steal incoming traffic, as a targetless agent is not connected to any Kubernetes service and does not
```

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +on your machine. You can use this fact to run management programs (like e.g. pgAdmin) and have them listen for
Is this an actual use case?

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +Moreover, the [environment variable used to specify a target](#using-an-environment-variable) has to be unset
Phrasing should be more like, "you should make sure the environment variable... isn't set".

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +> **Note:** In order to set the namespace the agent is going to be created in, set the agent namespace, not the
Perhaps this should just link to the configuration docs?

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +When targeting a deployment without specifying a container, the first container of the first pod found in the
Impersonating all pods in a deployment is supported in [mirrord for Teams](https://metalbear.co/#waitlist-form).

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +followed by optional `/container/<container-name>`. So for specifying a target without specifying a container you
```suggestion
optionally followed by `/container/<container-name>`. So for specifying a target without specifying a container you
```

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +You can specify a target namespace if the target should be found in that namespace instead of the namespace that is
I'd move this down to line 86 (see comment)

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +`target.namespace`.
```suggestion
`target.namespace`. By default, the namespace currently specified in the local `kubeconfig` is used.
```

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +If you are running from your IDE with the mirrord extension/plugin, and you didn't specify a target via a
```suggestion
If you are running one of mirrord's IDE extensions and you didn't specify a target via a
```

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +namespace than the one currently configured to be used by `kubectl`, you can set a target namespace in the
```suggestion
namespace you can set a target namespace in the
```

2023-05-19 10:14 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +[configuration file](#using-a-configuration-file), and the dialog will then contain potential targets out of that
```suggestion
[configuration file](#using-a-configuration-file), and the dialog will then contain targets in that
```

2023-05-19 14:51 UTC, t4lz commented on content/docs/reference/targets/index.md
> +environment variable.
Nice, thanks!

2023-05-19 14:51 UTC, t4lz commented on content/docs/reference/targets/index.md
> +> target namespace. That value can be set via the `agent.namespace` configuration file field, the -a CLI argument,
```suggestion
> target namespace. That value can be set via the `agent.namespace` [configuration file](https://mirrord.dev/docs/overview/configuration/) field, the -a CLI argument,
```

2023-05-19 14:51 UTC, t4lz commented on content/docs/reference/targets/index.md
> +deployment will be used.
```suggestion
deployment will be used (impersonating all pods in a deployment is supported in [mirrord for teams](https://metalbear.co/#waitlist-form)).
```

2023-05-19 14:51 UTC, t4lz commented on content/docs/reference/targets/index.md
> +
```suggestion
```

2023-05-19 14:51 UTC, t4lz commented on content/docs/reference/targets/index.md
> +You can specify a target namespace if the target should be found in that namespace instead of the namespace that is
Are you sure? Because line 86 talks about the configuration file specifically, and this line here only says that you can set the namespace and then each section (configuration, CLI, env var) tells the user how to set the namespace that way.

I think it's good for a reader to know at this point that they can set the namespace, and then jump to their preferred interface to see how exactly they can set it.

2023-05-19 14:57 UTC, t4lz commented on content/docs/reference/targets/index.md
> +When targeting a deployment without specifying a container, the first container of the first pod found in the
Added this sentence in line 51.

2023-05-19 14:57 UTC, t4lz commented on content/docs/reference/targets/index.md
> +Moreover, the [environment variable used to specify a target](#using-an-environment-variable) has to be unset
Changed to this phrasing.

2023-05-20 18:55 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +on your machine. You can use this fact to run management programs (like e.g. pgAdmin) and have them listen for
Just not familiar with it - does pgAdmin expose its UI on localhost or something?

2023-05-20 18:55 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +> **Note:** In order to set the namespace the agent is going to be created in, set the agent namespace, not the
Sure, haven't thought of that

2023-05-22 15:34 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +You can specify a target namespace if the target should be found in that namespace instead of the namespace that is
Okay convinced

2023-05-23 07:35 UTC, t4lz commented on content/docs/reference/targets/index.md
> +on your machine. You can use this fact to run management programs (like e.g. pgAdmin) and have them listen for
Changed it to be more general in https://github.com/metalbear-co/mirrord.dev/pull/76/commits/bd27045856f21e3c3de18f9983a9c82574119cc1.

2023-05-24 18:26 UTC, eyalb181 requested changes

2023-05-24 18:26 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +isn't set (or is set to an empty value) if you want to run targetless.
```suggestion
isn't set (or is set to an empty value).
```

2023-05-24 18:26 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +### Running without a target
The section order's a bit weird - since the page is about targets, I think "Running without a target" should be the last section, after Specifying a Target (and should be a ## header)

2023-05-24 19:58 UTC, t4lz commented on content/docs/reference/targets/index.md
> +### Running without a target
Done

2023-05-25 18:31 UTC, eyalb181 commented on content/docs/reference/targets/index.md
> +> target namespace. That value can be set via the [`agent.namespace` configuration file field](https://mirrord.dev/docs/overview/configuration/#agent-namespace), the -a CLI argument,
```suggestion
> target namespace. That value can be set via the [`agent.namespace` configuration file field](https://mirrord.dev/docs/overview/configuration/#agent-namespace), the `-a` CLI argument,
```

2023-05-25 21:05 UTC, eyalb181 approved these changes

2023-05-25 21:37 UTC, merged